version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: django-face-app:latest
    container_name: django-face-app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./static:/app/static
      - ./media:/app/media
      - ./upload:/app/upload
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=fer.webapps.digital,localhost,127.0.0.1
      - SECRET_KEY=your-secret-key-here-replace-this
      - SQLITE_DB_PATH=/app/db.sqlite3 