version: '3.8'

services:
  web:
    build: .
    container_name: django_face_recog
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./upload:/app/upload
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=False
      - SECRET_KEY=your_production_secret_key_here
      - ALLOWED_HOSTS=fer.webapps.digital,localhost,127.0.0.1
      - SQLITE_DB_PATH=/app/db.sqlite3 