version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3:rw
      - ./static:/app/staticfiles
      - ./upload:/app/media
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-default_dev_secret_key}
      - SQLITE_DB_PATH=/app/db.sqlite3
      - DJANGO_ALLOWED_HOSTS=fer.webapps.digital,www.fer.webapps.digital,localhost
    networks:
      - app-network
    user: "root"

networks:
  app-network:
    driver: bridge

volumes:
  static_volume:
  media_volume: 