version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8080:3500"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3:rw
      - ./static:/app/static:rw
      - ./static:/app/staticfiles:rw
      - ./upload:/app/media:rw
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY:-default_dev_secret_key}
      - SQLITE_DB_PATH=/app/db.sqlite3
    networks:
      - app-network
    user: "root"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3500/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

volumes:
  static_volume:
  media_volume: 