version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./static:/app/static
    environment:
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
      - ALLOWED_HOSTS=localhost,127.0.0.1,fer.webapps.digital
      - SQLITE_DB_PATH=/app/db.sqlite3
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3 